---
title: "BikeshareStrikeWrangling"
author: "Daniel Fuller"
date: '2018-04-25'
output:
      html_document:
        keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, error = FALSE, tidy = TRUE)
options(scipen = 2, digits=4)
```

## Merging the data from each city

```{r}
library(stringr)
library(knitr)
library(dplyr)
library(lubridate)
library(magrittr)

## Chicago - Divvy
divvy = list.files(path = "./Bikeshare Data/", pattern = "Divvy.*\\.csv")

### Washington - Cabi
cabi = list.files(path = "./Bikeshare Data/", pattern = "Cabi.*\\.csv")

### Philly - Indego
indeg = list.files(path = "./Bikeshare Data/", pattern = "Indego.*\\.csv")

### Boston - Hubway
hubway = list.files(path = "./Bikeshare Data/", pattern = "Hubway.*\\.csv")
```

## Chicago

```{r}
chicago <- divvy %>% 
    map(function(x) {
        read.csv(paste0("./Bikeshare Data/", x))
    }) %>%
    reduce(rbind)

chicago$city <- "Chicago"
head(chicago)

chicagoClean <- subset(chicago, select = c(trip_id, tripduration, starttime, stoptime, usertype, city), stringsAsFactors = FALSE)
names(chicagoClean) <- c("trip_id", "duration", "start_time", "end_time", "passholder_type", "city")
head(chicagoClean)

## Clean Start Time
chicagoClean$start_time <- gsub(" .*", "", chicagoClean$start_time)
chicagoClean$start_time <- mdy(chicagoClean$start_time)

## Clean End Time
chicagoClean$end_time <- gsub(" .*", "", chicagoClean$end_time)
chicagoClean$end_time <- mdy(chicagoClean$end_time)

head(chicagoClean)
```

## Boston

```{r}
boston <- hubway %>% 
    map(function(x) {
        read.csv(paste0("./Bikeshare Data/", x))
    }) %>%
    reduce(rbind)

boston$city <- "Boston"
boston$trip_id <- seq.int(nrow(boston))
head(boston)


bostonClean <- subset(boston, select = c(trip_id, tripduration, starttime, stoptime, usertype, city), stringsAsFactors = FALSE)
names(bostonClean) <- c("trip_id", "duration", "start_time", "end_time", "passholder_type", "city")
head(bostonClean)

## Clean Start Time
bostonClean$start_time <- gsub(" .*", "", bostonClean$start_time)
bostonClean$start_time <- ymd(bostonClean$start_time)

## Clean End Time
bostonClean$end_time <- gsub(" .*", "", bostonClean$end_time)
bostonClean$end_time <- ymd(bostonClean$end_time)

head(bostonClean)
```

##Philly
```{r}
philly <- indeg %>% 
    map(function(x) {
        read.csv(paste0("./Bikeshare Data/", x))
    }) %>%
    reduce(rbind)

philly$city <- "Philly"
head(philly)

phillyClean <- subset(philly, select = c(trip_id, duration, start_time, end_time, passholder_type, city), stringsAsFactors = FALSE)
names(phillyClean) <- c("trip_id", "duration", "start_time", "end_time", "passholder_type", "city")
head(phillyClean)

## Clean Start Time
phillyClean$start_time <- gsub(" .*", "", phillyClean$start_time)
phillyClean$start_time <- mdy(phillyClean$start_time)

## Clean End Time
phillyClean$end_time <- gsub(" .*", "", phillyClean$end_time)
phillyClean$end_time <- mdy(phillyClean$end_time)

head(phillyClean)
```

##Washington 
```{r}
washington <- cabi %>% 
    map(function(x) {
        read.csv(paste0("./Bikeshare Data/", x))
    }) %>%
    reduce(rbind)

washington$city <- "Washington"
head(washington)

washingtonClean <- subset(washington, select = c(trip_id, duration, start_time, end_time, passholder_type, city), stringsAsFactors = FALSE)
names(washingtonClean) <- c("trip_id", "duration", "start_time", "end_time", "passholder_type", "city")
head(washingtonClean)

## Clean Start Time
washingtonClean$start_time <- gsub(" .*", "", washingtonClean$start_time)
washingtonClean$start_time <- mdy(washingtonClean$start_time)

## Clean End Time
washingtonClean$end_time <- gsub(" .*", "", washingtonClean$end_time)
washingtonClean$end_time <- mdy(washingtonClean$end_time)

head(washingtonClean)
```

## Appending data
```{r}
strikeData <- rbind(chicagoClean, phillyClean, washingtonClean, bostonClean)
strikeData <- filter(strikeData, year > 2015)
head(strikeData)

write.csv(strikeData, file = "strikeData.csv")
```

## Cleaning and recoding

```{r}
strikeData$month <- month(strikeData$start_time)
strikeData$day <- day(strikeData$start_time)
strikeData$year <- year(strikeData$start_time)


##add dummy to CityColl

strikeData$dummy <-  ifelse(strikeData$start_time >= as.Date("2016/11/01", format = "%Y/%m/%d"), 1, 0)

strikeData$memberType <- recode_factor(strikeData$passholder_type, 
                                    `Customer` = "shortterm",
                                    `Subscriber` = "member",
                                     `Indego30` = "member",
                                     `IndegoFlex` = "shortterm",
                                     `Walk-up` = "shortterm", 
                                     `Registered` = "member",
                                     `Casual` = "shortterm",
                                     `Dependent` = "shortterm",
                                     `Member` = "member")

table(strikeData$memberType, strikeData$passholder_type)

table(strikeData$passholder_type)
```

```{r}
city_day_sum <- strikeData %>% 
                    group_by(year, month, day, city) %>% 
                          mutate(mDuration = mean(duration, na.rm = TRUE), 
                                    number_trips = n())  %>% 
                          distinct(year, month, day, city, .keep_all=TRUE)

##Normalize by city pop
## Boston - 667137 (6.67137)
## Chicago - 2695598 (26.95598)
## Washington - 672228 (6.72228)
## Philly - 1567872 (15.67872)

city_day_sum$by100000 <-
        ifelse(city_day_sum$city == "Philly", city_day_sum$number_trips/15.67872, NA) %>%
        ifelse(city_day_sum$city == "Washington", city_day_sum$number_trips/6.72228, .) %>%
        ifelse(city_day_sum$city == "Chicago", city_day_sum$number_trips/26.95598, .) %>%
        ifelse(city_day_sum$city == "Boston", city_day_sum$number_trips/6.67137, .) 

city_day_sum <- arrange(city_day_sum, start_time)

write.csv(city_day_sum, "city_day_sum1.csv")



strikeData1$date = dmy(paste(strikeData1$day, strikeData1$month, strikeData1$year))

library(ggplot2)

test <- ggplot(strikeData1, aes(x = date, y = total)) + geom_rect(aes(xmin = as.Date("2016-11-01",
                                                                                     format = "%Y-%m-%d"), xmax = as.Date("2016-11-07", format = "%Y-%m-%d"),
                                                                      ymin = 0, ymax = Inf), alpha = 0.9, fill = "grey") + geom_line(aes(color = factor(city))) +
  theme(axis.line = element_line(colour = "black"), panel.background = element_blank(),
        axis.title = element_text(size = 16), text = element_text(size = 14)) +
  xlab("Date") + ylab("Number of Trips per Day") +
  scale_colour_discrete(name = "Cities", breaks = c("Chicago", "Philly", "Washington", "Boston"), labels = c("Chicago", "Philly", "Washington", "Boston"))

print(test)

write.csv(strikeData, file = "StrikeDatafour.csv")

strikeData2 <- strikeData %>% group_by(year, month, day, city, memberType) %>% summarise(sumDuration = sum(duration,
                                                                                               na.rm = TRUE), mDuration = mean(duration, na.rm = TRUE), total = n())
strikeData2$date = dmy(paste(strikeData2$day, strikeData2$month, strikeData2$year))

test2 <- ggplot(strikeData2, aes(x = date, y = total)) + geom_rect(aes(xmin = as.Date("2016-11-01",
                                                                                     format = "%Y-%m-%d"), xmax = as.Date("2016-11-07", format = "%Y-%m-%d"),
                                                                      ymin = 0, ymax = Inf), alpha = 0.9, fill = "grey") + geom_line(aes(color = factor(memberType))) +
  theme(axis.line = element_line(colour = "black"), panel.background = element_blank(),
        axis.title = element_text(size = 16), text = element_text(size = 14)) +
  xlab("Date") + ylab("Number of Trips per Day") +
  scale_colour_discrete(name = "Member Type", breaks = c("member", "shortterm"), labels = c("Member", "Short Term"))

print(test2)

##Export data

write.table(strikeData, "C:/Users/Richard Buote/Desktop/strikeData.csv", sep=",")
write.table(summarytest, "C:/Users/Richard Buote/Desktop/summarytest.csv", sep=",")


##by day, trips, and duration

summarytest <- strikeData %>%
  group_by(start_time) %>%
  summarize(mean_duration = mean(duration), number_trips = n())

##Collapse Data

bostoncoll <- bostonClean %>%
  group_by(start_time) %>%
  summarize(mean_duration = mean(duration), number_trips = n())

bostoncoll$city <- "Boston"

chicagocoll <- chicagoClean %>%
  group_by(start_time) %>%
  summarize(mean_duration = mean(duration), number_trips = n())

chicagocoll$city <- "Chicago"

washingtoncoll <- washingtonClean %>%
  group_by(start_time) %>%
  summarize(mean_duration = mean(duration), number_trips = n())

washingtoncoll$city <- "Washington"

phillycoll <- phillyClean %>%
  group_by(start_time) %>%
  summarize(mean_duration = mean(duration), number_trips = n())

phillycoll$city <- "Philly"

##Normalize by city pop
## Boston - 667137 (6.67137)
## Chicago - 2695598 (26.95598)
## Washington - 672228 (6.72228)
## Philly - 1567872 (15.67872)

bostoncoll$by100000 <- bostoncoll$number_trips/6.67137
chicagocoll$by100000 <- chicagocoll$number_trips/26.95598
washingtoncoll$by100000 <- washingtoncoll$number_trips/6.72228
phillycoll$by100000 <- phillycoll$number_trips/15.67872



CityColl <- rbind(bostoncoll, chicagocoll, washingtoncoll, phillycoll)

##Remove before 2015 and order by date

CityColl$start_time <- as.Date(CityColl$start_time, format= "%Y-%m-%d")
CityColl <- subset(CityColl, start_time > "2015-12-31")
CityColl <- CityColl[order(as.Date(CityColl$start_time, format = "%Y-%m-%d")),]

ggplot(CityColl, aes(x = start_time, y = by100000, group = city, color = city)) +
  geom_line()

phillycoll$start_time <- as.Date(phillycoll$start_time, format= "%Y-%m-%d")
phillycoll <- subset(phillycoll, start_time > "2015-12-31")

chicagocoll$start_time <- as.Date(chicagocoll$start_time, format= "%Y-%m-%d")
chicagocoll <- subset(chicagocoll, start_time > "2015-12-31")

washingtoncoll$start_time <- as.Date(washingtoncoll$start_time, format= "%Y-%m-%d")
washingtoncoll <- subset(washingtoncoll, start_time > "2015-12-31")


```