---
title: "Philly Bikeshare Analysis"
author: "Daniel Fuller"
date: "September 1, 2017"
output:
      html_document:
        keep_md: true
---

```{r}
library(stringr)
library(knitr)
library(dplyr)
library(lubridate)
library(ggplot2)
library(forecast)
library(tseries)
library(formatR)
library(CausalImpact)
library(zoo)

options(scipen = 2, digits=4)
opts_chunk$set(warning = FALSE, message = FALSE, error = FALSE, tidy = TRUE)
```

```{r}
city_data <- read.csv("https://raw.githubusercontent.com/walkabilly/Phillybikeshare/master/CityColl.csv")
member_data <- read.csv("https://raw.githubusercontent.com/walkabilly/Phillybikeshare/master/MemberColl.csv")
final_data <- read.csv("https://raw.githubusercontent.com/walkabilly/Phillybikeshare/master/city_day_sum.csv")
phil_temp16 <- read.csv("https://raw.githubusercontent.com/walkabilly/Phillybikeshare/master/Phil_temp_2016.csv")

### Convert start_time from factor to date
city_data$start_time <- mdy(city_data$start_time)
member_data$start_time <- mdy(member_data$start_time)
```

### Time Series Plot 

#### All bikeshare users (members and non-members)

```{r}
cityplot <- ggplot(data = city_data, aes(x = start_time, y = by100000)) +
  geom_line() +
  stat_smooth(aes(group = dummy), method = "lm", formula = y ~ poly(x, 2), se = FALSE) +
  geom_vline(xintercept=as.numeric(city_data$start_time[1398]), linetype=4) + 
  facet_wrap(~ city) + 
  theme_classic()
  

plot(cityplot)
```

#### Data cleaning Bikeshare member type by city

#### Philadelphia

```{r}
philly_data <- filter(member_data, city == "Philly")

philly_member_plot <- ggplot(data = philly_data, aes(x = start_time, y = by10000)) +
  geom_line() +
  stat_smooth(aes(group = dummy), method = "lm", formula = y ~ poly(x, 2), se = FALSE) +
  geom_vline(xintercept=as.numeric(city_data$start_time[1398]), linetype=4) + 
  facet_wrap(~ membertype) + 
  theme_classic()
  
plot(philly_member_plot)
```

#### Boston

```{r}
boston_data <- filter(member_data, city == "Boston")

boston_member_plot <- ggplot(data = boston_data, aes(x = start_time, y = by10000)) +
  geom_line() +
  stat_smooth(aes(group = dummy), method = "lm", formula = y ~ poly(x, 2), se = FALSE) +
  geom_vline(xintercept=as.numeric(city_data$start_time[1398]), linetype=4) + 
  facet_wrap(~ membertype) + 
  theme_classic()
  
plot(boston_member_plot)
```

#### Chicago

```{r}
chicago_data <- filter(member_data, city == "Chicago")

chicago_member_plot <- ggplot(data = chicago_data, aes(x = start_time, y = by10000)) +
  geom_line() +
  stat_smooth(aes(group = dummy), method = "lm", formula = y ~ poly(x, 2), se = FALSE) +
  geom_vline(xintercept=as.numeric(city_data$start_time[1398]), linetype=4) + 
  facet_wrap(~ membertype) + 
  theme_classic()
  
plot(chicago_member_plot)
```

#### Washington

```{r}
Washington_data <- filter(member_data, city == "Washington")

washington_member_plot <- ggplot(data = Washington_data, aes(x = start_time, y = by10000)) +
  geom_line() +
  stat_smooth(aes(group = dummy), method = "lm", formula = y ~ poly(x, 2), se = FALSE) +
  geom_vline(xintercept=as.numeric(city_data$start_time[1398]), linetype=4) + 
  facet_wrap(~ membertype) + 
  theme_classic()
  
plot(washington_member_plot)
```

###3. Data analysis
###3.1 Linear Model

```{r}
lm2citycoll <- lm(number_trips ~ start_time + dummy + start_time*dummy, data=city_data)
summary(lm2citycoll)

lm3citycoll <- lm(number_trips ~ start_time + dummy + city + start_time*dummy + city*dummy, data=city_data)
summary(lm3citycoll)

lm2by100k <- lm(by100000 ~ start_time + dummy + start_time*dummy, data=city_data)
summary(lm2by100k)

lm3by100k <- lm(by100000 ~ start_time + dummy + city + start_time*dummy + city*dummy, data=city_data)
summary(lm3by100k)
```

```
##Boston Moving Average

bostoncoll$Date = as.Date(bostoncoll$start_time)

ggplot(bostoncoll, aes(Date, by100000)) +
  geom_line() +
  scale_x_date('month') +
  ylab("Number of Trips") +
  xlab("")

##Data clean, smoothing outliers

bostoncount_ts = ts(bostoncoll[, c('by100000')])

bostoncoll$clean_cnt = tsclean(as.vector(bostoncount_ts))

ggplot() +
  geom_line(data = bostoncoll, aes(x = Date, y = clean_cnt)) +
  ylab('Cleaned Number of Trips')

#using the clean count with no outliers

bostoncoll$cnt_ma = ma(bostoncoll$clean_cnt, order=7) 

bostoncoll$cnt_ma30 = ma(bostoncoll$clean_cnt, order=30)

ggplot() +
  geom_line(data = bostoncoll, aes(x = Date, y = clean_cnt, colour = "Counts")) +
  geom_line(data = bostoncoll, aes(x = Date, y = cnt_ma,   colour = "Weekly Moving Average"))  +
  geom_line(data = bostoncoll, aes(x = Date, y = cnt_ma30, colour = "Monthly Moving Average"))  +
  ylab('Number of Trips x 100000 person')

##Chicago Moving Average

chicagocoll$Date = as.Date(chicagocoll$start_time)

ggplot(chicagocoll, aes(Date, by100000)) +
  geom_line() +
  scale_x_date('month') +
  ylab("Number of Trips") +
  xlab("")

##Data clean, smoothing outliers

chicagocount_ts = ts(chicagocoll[, c('by100000')])

chicagocoll$clean_cnt = tsclean(as.vector(chicagocount_ts))

ggplot() +
  geom_line(data = chicagocoll, aes(x = Date, y = clean_cnt)) +
  ylab('Cleaned Number of Trips')

#using the clean count with no outliers

chicagocoll$cnt_ma = ma(chicagocoll$clean_cnt, order=7) 

chicagocoll$cnt_ma30 = ma(chicagocoll$clean_cnt, order=30)

ggplot() +
  geom_line(data = chicagocoll, aes(x = Date, y = clean_cnt, colour = "Counts")) +
  geom_line(data = chicagocoll, aes(x = Date, y = cnt_ma,   colour = "Weekly Moving Average"))  +
  geom_line(data = chicagocoll, aes(x = Date, y = cnt_ma30, colour = "Monthly Moving Average"))  +
  ylab('Number of Trips x 100000 person')

##Washington moving average

washingtoncoll$Date = as.Date(washingtoncoll$start_time)

ggplot(washingtoncoll, aes(Date, by100000)) +
  geom_line() +
  scale_x_date('month') +
  ylab("Number of Trips") +
  xlab("")

##Data clean, smoothing outliers

washcount_ts = ts(washingtoncoll[, c('by100000')])

washingtoncoll$clean_cnt = tsclean(as.vector(washcount_ts))

ggplot() +
  geom_line(data = washingtoncoll, aes(x = Date, y = clean_cnt)) +
  ylab('Cleaned Number of Trips')

#using the clean count with no outliers

washingtoncoll$cnt_ma = ma(washingtoncoll$clean_cnt, order=7) 

washingtoncoll$cnt_ma30 = ma(washingtoncoll$clean_cnt, order=30)

ggplot() +
  geom_line(data = washingtoncoll, aes(x = Date, y = clean_cnt, colour = "Counts")) +
  geom_line(data = washingtoncoll, aes(x = Date, y = cnt_ma,   colour = "Weekly Moving Average"))  +
  geom_line(data = washingtoncoll, aes(x = Date, y = cnt_ma30, colour = "Monthly Moving Average"))  +
  ylab('Number of Trips x 100000 person')

##Philly Moving Average

phillycoll$Date = as.Date(phillycoll$start_time)

ggplot(phillycoll, aes(Date, by100000)) +
  geom_line() +
  scale_x_date('month') +
  ylab("Number of Trips") +
  xlab("")

##Data clean, smoothing outliers

phillycount_ts = ts(phillycoll[, c('by100000')])

phillycoll$clean_cnt = tsclean(as.vector(phillycount_ts))

ggplot() +
  geom_line(data = phillycoll, aes(x = Date, y = clean_cnt)) +
  ylab('Cleaned Number of Trips')

#using the clean count with no outliers

phillycoll$cnt_ma = ma(phillycoll$clean_cnt, order=7) 

phillycoll$cnt_ma30 = ma(phillycoll$clean_cnt, order=30)

ggplot() +
  geom_line(data = phillycoll, aes(x = Date, y = clean_cnt, colour = "Counts")) +
  geom_line(data = phillycoll, aes(x = Date, y = cnt_ma,   colour = "Weekly Moving Average"))  +
  geom_line(data = phillycoll, aes(x = Date, y = cnt_ma30, colour = "Monthly Moving Average"))  +
  ylab('Number of Trips x 100000 person')

##Decompose data

count_ma = ts(na.omit(bostoncoll$cnt_ma), frequency=30)
decomp = stl(count_ma, s.window="periodic")
deseasonal_cnt <- seasadj(decomp)
plot(decomp)

##Dickey Fuller Test

adf.test(count_ma, alternative = "stationary")

## Auto-correlation plots

Acf(count_ma, main='')

Pacf(count_ma, main='')

count_d1 = diff(deseasonal_cnt, differences = 1)
plot(count_d1)
adf.test(count_d1, alternative = "stationary")

Acf(count_d1, main='ACF for Differenced Series')

Pacf(count_d1, main='PACF for Differenced Series')

##ARIMA test

auto.arima(deseasonal_cnt, seasonal=FALSE)

fit<-auto.arima(deseasonal_cnt, seasonal=FALSE)

par(mar = rep(2, 4))

tsdisplay(residuals(fit), lag.max=45, main='(1,1,1) Model Residuals')

fit2 = arima(deseasonal_cnt, order=c(1,1,7))

fit2

tsdisplay(residuals(fit2), lag.max=15, main='Seasonal Model Residuals')

fcast <- forecast(fit2, h=30)
plot(fcast)

hold <- window(ts(deseasonal_cnt), start=200)

fit_no_holdout = arima(ts(deseasonal_cnt[-c(200:725)]), order=c(1,1,7))

fcast_no_holdout <- forecast(fit_no_holdout,h=170)
plot(fcast_no_holdout, main=" ")
lines(ts(deseasonal_cnt))

fit_w_seasonality = auto.arima(deseasonal_cnt, seasonal=TRUE)
fit_w_seasonality
seas_fcast <- forecast(fit_w_seasonality, h=30)
plot(seas_fcast)
```
##Philly CausalImpact---------------------
```{r}
Phil_dat <- filter(final_data, city=="Philly")
##Add records for the missing two days
Phil_dat[365, "start_time"] <- "2016-01-23"
Phil_dat[366, "start_time"] <- "2016-01-24"
##Arrange the data based on time
Phil_dat <- arrange(Phil_dat,start_time)

##Set pre- and post-periods
pre.period <- as.Date(c("2016-01-01", "2016-10-31"))
post.period <- as.Date(c("2016-11-01", "2016-12-31"))
post.period2 <- as.Date(c("2016-11-01", "2016-11-07")) ##Assess the impact one week after the strike

##Modelling all Phil data
Phil_dat$start_time <- as.Date(Phil_dat$start_time)

data <- zoo(cbind(Phil_dat$by100000, avgTemp_16$MEAN), as.Date(Phil_dat$start_time))

##Modelling without covaraites
impact_phil <- CausalImpact(data = data[,1], pre.period = pre.period, post.period = post.period, model.args = list(niter=5000, nseasons=7))
##Post-period set as one week after the strike
impact_phil2 <- CausalImpact(data = data[,1], pre.period = pre.period, post.period = post.period2, model.args = list(niter=5000, nseasons=7))
##Modelling with covaraites: temperature
impact_phil3 <- CausalImpact(data = data, pre.period = pre.period, post.period = post.period, model.args = list(niter=5000, nseasons=7))
# ##Dynamic regression: whether to include a time-varying regression coefficient. Default is FALSE
# impact_phil4 <- CausalImpact(data = data, pre.period = pre.period, post.period = post.period, model.args = list(niter=5000, nseasons=7, dynamic.regression=T))
# ##Control monthly effect
# impact_phil5 <- CausalImpact(data = data, pre.period = pre.period, post.period = post.period, model.args = list(niter=5000, nseasons=12, season.duration= 30))
# ##Control seasonal effect
# impact_phil6 <- CausalImpact(data = data, pre.period = pre.period, post.period = post.period, model.args = list(niter=5000, nseasons=4))

plot(impact_phil)
plot(impact_phil3)
# plot(impact_phil4) ##Not a good fit!!!
# plot(impact_phil5) ##Not a good fit!!!
# plot(impact_phil6) ##Not a good fit!!!


##Modelling Philadelphia data based on membership
member_bs <- read.csv("MemberColl.csv")
member_bs$start_time <- as.Date(member_bs$start_time, "%m/%d/%Y")
phil_bs_mem <- filter(member_bs, city=="Philly" & membertype == "member" & start_time > "2016-01-24")
phil_bs_nonmem <- filter(member_bs, city=="Philly" & membertype == "shortterm" & start_time > "2016-01-24")

data_mem <- zoo(cbind(phil_bs_mem$by10000), phil_bs_mem$start_time)

impact_pil_mem <- CausalImpact(data = data_mem, pre.period = pre.period, post.period = post.period, model.args = list(niter=5000, nseasons=7))
```
##Boston data analysis----------------------------
```{r}
Boston_dat <- filter(final_data, city=="Boston")
Boston_dat$start_time <- as.Date(Boston_dat$start_time)

data_bos <- zoo(cbind(Boston_dat$by100000), as.Date(Boston_dat$start_time))

impact_bos <- CausalImpact(data = data_bos, pre.period = pre.period, post.period = post.period, model.args = list(niter=5000, nseasons=7))

plot(impact_bos)
```
##Chicago data anlysis ---------------------------
```{r}
Chicago_dat <- filter(final_data, city=="Chicago")
Chicago_dat$start_time <- as.Date(Chicago_dat$start_time)

data_chi <- zoo(cbind(Chicago_dat$by100000), as.Date(Chicago_dat$start_time))

impact_chi <- CausalImpact(data = data_chi, pre.period = pre.period, post.period = post.period, model.args = list(niter=5000, nseasons=7))

plot(impact_chi)  ##Not a good fit to the data
```
##Washington data anlysis ---------------------------
```{r}
DC_dat <- filter(final_data, city=="Washington")  ##Missing four days' data
DC_dat[363, "start_time"] <- "2016-01-23"
DC_dat[364, "start_time"] <- "2016-01-24"
DC_dat[365, "start_time"] <- "2016-01-25"
DC_dat[366, "start_time"] <- "2016-01-26"

DC_dat$start_time <- as.Date(DC_dat$start_time)
DC_dat <- arrange(DC_dat, start_time)

data_DC <- zoo(cbind(DC_dat$by100000), as.Date(DC_dat$start_time))

impact_DC <- CausalImpact(data = data_DC, pre.period = pre.period, post.period = post.period, model.args = list(niter=5000,nseasons=7))

plot(impact_DC)  ##Not a good fit to the data
```


